import React from 'react';
import { BarChart3, Search, Layers, GraduationCap, Printer, Calculator } from 'lucide-react';
import { Scanner, BarcodePrinter, Ribbon, Lesson, PrinterAccessory } from './types';

export const SCANNERS: Scanner[] = [
  {
    id: 'honeywell-1950ghd',
    name: 'Honeywell 1950GHD',
    brand: 'Honeywell',
    type: 'Máy quét 1D/2D',
    retailPrice: '3.100.000 VNĐ',
    dealerPrice: '2.800.000 VNĐ',
    speed: 'Cực cao',
    durability: 'IP52 (Rơi 1.8m)',
    distance: 'Tầm gần tiêu chuẩn',
    application: 'Điểm bán hàng, Kiểm kê',
    pros: ['Độ chính xác tuyệt vời', 'Cáp dài 3m', 'Thiết kế bền bỉ'],
    cons: ['Dây cáp dài 3m'],
    isWireless: false,
    isLongRange: false,
    sensorResolution: '1280 x 800 pixels',
    isPDA: false,
    specialFeatures: ['IP52', 'cáp dài 3m'],
    stock: 47,
    isPriority: true,
    imageUrl: 'https://binhduongbarcode.com/thumbs/540x540x1/upload/product/honeywell-ghd-1950-2249.png',
    warranty: '12 tháng',
    unit: 'Cái',
    accessories: ['Cáp USB']
  },
    {
    id: 'idata-j17',
    name: 'Idata J17',
    brand: 'Idata',
    type: 'Máy quét 1D/2D có dây',
    retailPrice: '2.700.000',
    dealerPrice: '2.390.000',
    speed: '',
    durability: 'IP67',
    distance: '',
    application: 'Bán lẻ, Kho hàng',
    pros: ['Quét 1D/2D/QR', 'Bảo hành 24 tháng', 'Cáp dài 2m'],
    cons: ['Có dây'],
    isWireless: false,
    isLongRange: false,
    sensorResolution: '1920 x 800 pixels',
    isPDA: false,
    specialFeatures: ['Quét tự động'],
    stock: 15,
    isPriority: true,
    imageUrl: 'https://binhduongbarcode.com/thumbs/540x540x1/upload/product/idata-j17-may-quet-co-day-cam-tay-3479.png',
    warranty: '12 tháng',
    unit: 'Cái',
    accessories: ['Chân đế', 'Cáp USB'],
  },
  {
     id: 'zebra-ds8108',
    name: 'Zebra DS8108',
    brand: 'Zebra',
    type: 'Máy quét 2D có dây',
    retailPrice: '4.300.000',
    dealerPrice: '3.600.000',
    speed: '',
    durability: 'IP42',
    distance: '',
    application: 'Bán lẻ cao cấp',
    pros: ['Quét cực nhanh', 'Đọc mã vạch hỏng tốt', 'Thiết kế sang trọng'],
    cons: ['Giá cao'],
    isWireless: false,
    isLongRange: false,
    sensorResolution: '1280 x 960 pixels',
    isPDA: false,
    specialFeatures: ['IP52', 'Rơi 1.8m'],
    stock: 18,
    isPriority: true,
    imageUrl: 'https://binhduongbarcode.com/thumbs/540x540x1/upload/product/zebra-ds8108-9142.jpg',
    warranty: '12 tháng',
    unit: 'Cái',
    accessories: ['Cáp USB']
  },
   {
    id: 'syble-xb-6208rb',
    name: 'Syble XB-6208RB',
    brand: 'Syble',
    type: 'Máy quét 2D không dây',
    retailPrice: '1.710.000',
    dealerPrice: '1.485.000',
    speed: '',
    durability: '',
    distance: '30-50m',
    application: 'Kho bãi, Siêu thị',
    pros: ['Không dây', 'Quét 1D/2D/QR', 'Bảo hành 24 tháng', 'Tầm xa 50m'],
    cons: ['quét căn cước công dân'],
    isWireless: true,
    isLongRange: false,
    sensorResolution: '640 x 480 pixels',
    isPDA: false,
    specialFeatures: ['Bluetooth', 'USB-HID'],
    stock: 10,
    isPriority: true,
    imageUrl: 'https://binhduongbarcode.com/upload/elfinder/may-quet-xb-6208rb-3.jpg',
    warranty: '24 tháng',
    unit: 'Cái',
    accessories: ['Chân đế', 'Cáp USB'],
  },
  {
    id: 'idata-k3s',
    name: 'iData K3S',
    brand: 'iData',
    type: 'PDA / Máy kiểm kho',
    retailPrice: '6.100.000 VNĐ',
    dealerPrice: '5.850.000 VNĐ',
    speed: 'Octa-core 2.0 GHz',
    durability: 'IP65',
    distance: 'quét xa 2m',
    application: 'Logistics, Kho bãi',
    pros: ['Bàn phím cứng bền bỉ', 'Hiệu suất cao', 'Giá PDA cạnh tranh'],
    cons: ['Nặng hơn điện thoại thông thường'],
    isWireless: true,
    isLongRange: false,
    sensorResolution: '8MP Camera',
    isPDA: true,
    specialFeatures: ['IP65', 'Bàn phím'],
    screenSize: '4.0 inch',
    ram: '4GB/64GB',
    cpu: 'Octa-core 2.0GHz',
    stock: 11,
    isPriority: true,
    imageUrl: 'https://binhduongbarcode.com/thumbs/540x540x1/upload/product/idata-k3s-8056.png',
    warranty: '12 tháng',
    unit: 'Cái',
    accessories: ['Dây đeo mặt sau', 'Cáp Type C','Củ sạc',],
  },
  
  {
    id: 'idata-t1-pro',
    name: 'iData T1 Pro',
    brand: 'iData',
    type: 'PDA / Máy kiểm kho',
    retailPrice: '6.380.000',
    dealerPrice: '5.800.000',
    speed: 'Octa-core',
    durability: 'IP67/IP65',
    distance: ' tầm gần tiêu chuẩn',
    application: 'Kiểm kho, Bán lẻ',
    pros: ['Android 14', '5.5 inch cảm ứng', 'Pin 5000mAh', '4G + GPS'],
    cons: [],
    isWireless: true,
    isLongRange: false,
    sensorResolution: '>3.3mil',
    isPDA: true,
    specialFeatures: ['Wifi + 4G', 'Bluetooth', 'GSM', 'GPS'],
    screenSize: '5.5 inch',
    ram: '64GB + 4GB (standard)',
    cpu: 'Octa-core 2.0GHz',
    stock: 16,
    isPriority: true,
    imageUrl: 'https://binhduongbarcode.com/upload/elfinder/idata-T1-Pro%20%283%29.JPEG',
    warranty: '12 tháng',
    unit: 'Cái',
    accessories: ['Cụ sạc', 'Cáp']
  },
  {
    id: 'honeywell-eda52',
    name: 'Honeywell EDA52',
    brand: 'Honeywell',
    type: 'PDA / Máy kiểm kho',
    retailPrice: '12.925.000',
    dealerPrice: '11.750.000',
    speed: 'Octa-core 2.0 GHz',
    durability: 'IP67',
    distance: 'Tầm gần tiêu chuẩn',
    application: 'Bán lẻ, Giao nhận, Kiểm kho',
    pros: ['Thiết kế công thái học', 'Giá/hiệu năng tốt', 'Màn hình 5.5 inch'],
    cons: ['Hỗ trợ phiên bản Android hạn chế'],
    isWireless: true,
    isLongRange: false,
    sensorResolution: '13MP',
    isPDA: true,
    specialFeatures: ['Android', 'IP64'],
    screenSize: '5.0 inch',
    ram: '3/32 GB, 4/64 GB, 6/128 GB',
    cpu: 'Qualcomm Snapdragon SM6115 ',
    stock: 10,
    isPriority: true,
    imageUrl: 'https://binhduongbarcode.com/thumbs/540x540x1/upload/product/may-kiem-kho-di-dong-pda-honeywell-eda52-6854.png',
    warranty: '12 tháng',
    unit: 'Cái'
  },
   {
    id: 'zebra-tc22',
    name: 'Zebra TC22',
    brand: 'Zebra',
    type: 'PDA / Máy kiểm kho',
    retailPrice: '11.250.000',
    dealerPrice: '10.500.000',
    speed: '',
    durability: 'IP68 & IP65',
    distance: 'Tầm gần tiêu chuẩn',
    application: 'Bán lẻ, Giao nhận, Kiểm kho, Logistics',
    pros: ['Màn hình lớn 6 inch', 'Hiệu năng tốt', 'Pin trâu'],
    cons: ['Giá cao'],
    isWireless: true,
    isLongRange: false,
    sensorResolution: '13MP',
    isPDA: true,
    specialFeatures: ['Hiệu năng cao', 'Màn hình lớn'],
    screenSize: '6.0 inch',
    ram: '6/64 GB, 8/128 GB',
    cpu: 'Qualcomm™ 5430 hex-core, 2.1 GHz ',
    stock: 0,
    isPriority: true,
    imageUrl: 'https://binhduongbarcode.com/upload/elfinder/tc22-tc27-photography-product-eight-pin-front-left-facing-up-3x2-3600.jpg',
    warranty: '12 tháng',
    unit: 'Cái'
  },
  {
    id: 'idata-t1-uhf',
    name: 'iData T1 UHF',
    brand: 'iData',
    type: 'PDA RFID',
    retailPrice: '13.200.000',
    dealerPrice: '11.900.000',
    speed: 'Octa-core',
    durability: 'IP67',
    distance: 'đọc RFID 30m',
    application: 'Kiểm kho RFID',
    pros: ['Android 14', '5.5 inch', 'Pin khủng 11.700mAh', 'Đọc RFID'],
    cons: ['Giá cao'],
    isWireless: true,
    isLongRange: false,
    sensorResolution: 'màn hình 1440*720 pixels',
    isPDA: true,
    specialFeatures: ['RFID', 'Wifi + 4G', 'GPS'],
    screenSize: '5.5 inch',
    ram: '4 GB + 64 GB',
    cpu: '8 core 2.0 GHz',
    stock: 23,
    isPriority: true,
    imageUrl: 'https://binhduongbarcode.com/thumbs/540x540x1/upload/product/thiet-ke-chua-co-ten-5593.png',
    warranty: '12 tháng',
    unit: 'Cái',
    accessories: ['Dock sạc mua riêng 32 USD', 'Dây nguồn', 'Cáp'],
  },
  {
     id: 'zebra-ds2208',
    name: 'Zebra DS2208',
    brand: 'Zebra',
    type: 'Máy quét 2D có dây',
    retailPrice: '1.990.000',
    dealerPrice: '1.680.000',
    speed: '',
    durability: '',
    distance: '',
    application: 'Bán lẻ, Y tế',
    pros: ['Thương hiệu Zebra', 'Quét nhanh', 'Đọc mã vạch trên màn hình'],
    cons: ['Có dây', 'Giá cao hơn'],
    isWireless: false,
    isLongRange: false,
    sensorResolution: '',
    isPDA: false,
    specialFeatures: [],
    stock: 0,
    isPriority: false,
    imageUrl: 'https://binhduongbarcode.com/thumbs/540x540x1/upload/product/zebra-ds2208-4-7668.jpg',
    warranty: '12 tháng',
    unit: 'Cái',
    accessories: ['Chân đế', 'Cáp USB'],
  },
  {
    id: 'zebra-ds8178',
    name: 'Zebra DS8178',
    brand: 'Zebra',
    type: 'Máy quét 2D không dây',
    retailPrice: '7.300.000',
    dealerPrice: '6.850.000',
    speed: '',
    durability: '',
    distance: '50-100m',
    application: 'Bán lẻ, Kho bãi',
    pros: ['Không dây', 'Tầm xa 100m', 'Pin PowerPrecision+', 'Quét nhanh'],
    cons: ['Rất đắt'],
    isWireless: true,
    isLongRange: true,
    sensorResolution: '',
    isPDA: false,
    specialFeatures: ['Bluetooth', 'USB', 'IP52'],
    stock: 1,
    isPriority: false,
    imageUrl: 'https://binhduongbarcode.com/thumbs/540x540x1/upload/product/zebra-ds8178-5057.png',
    warranty: '12 tháng',
    unit: 'Cái',
    accessories: ['Chân đế', 'Dây cáp']
  },
  {
    id: 'zebra-tc21',
    name: 'Zebra TC21',
    brand: 'Zebra',
    type: 'PDA / Máy kiểm kho',
    retailPrice: '12.000.000 VNĐ',
    dealerPrice: '10.500.000 VNĐ',
    speed: 'Octa-core 1.8 GHz',
    durability: 'IP67 (Rơi 1.2m)',
    distance: 'Tầm gần tiêu chuẩn',
    application: 'Giao hàng, Kiểm kho, Bán lẻ',
    pros: ['Hệ điều hành Android', 'Màn hình cảm ứng lớn', 'Pin có thể tháo rời'],
    cons: ['Cần quản lý MDM cho số lượng lớn'],
    isWireless: true,
    isLongRange: false,
    sensorResolution: '13MP Sau / 5MP Trước',
    isPDA: true,
    specialFeatures: ['Android', 'IP67', 'Cảm ứng'],
    screenSize: '5.0 inch HD',
    ram: '3GB/4GB',
    cpu: 'Snapdragon 660',
    stock: 12,
    isPriority: true,
    imageUrl: 'https://binhduongbarcode.com/thumbs/540x540x1/upload/product/may-kiem-kho-di-dong-1056.jpg',
    warranty: '12 tháng',
    unit: 'Cái',
    accessories: ['Tay cầm (Trigger)', 'Pin dự phòng']
  },
  {
    id: 'mobydata-v31',
    name: 'Mobydata V31 (M71)',
    brand: 'Mobydata',
    type: 'PDA / Máy kiểm kho',
    retailPrice: '6.650.000',
    dealerPrice: '5.900.000',
    speed: '',
    durability: '',
    distance: '',
    application: 'Kiểm kho cơ bản',
    pros: ['Android 9', 'Bàn phím 23 phím', 'Pin 4000mAh', 'Giá rẻ'],
    cons: ['Cấu hình thấp (2GB/16GB)'],
    isWireless: true,
    isLongRange: false,
    sensorResolution: '',
    isPDA: true,
    specialFeatures: ['Wifi + 4G'],
    screenSize: '4.0 inch',
    ram: '2 GB',
    cpu: '',
    stock: 0,
    isPriority: false,
    imageUrl: '',
    warranty: '',
    unit: 'Cái',
    accessories: ['Cụ sạc', 'Cáp'],
  },
  {
    id: 'mobydata-v32',
    name: 'Mobydata V32 (M72)',
    brand: 'Mobydata',
    type: 'PDA / Máy kiểm kho',
    retailPrice: '.',
    dealerPrice: '.',
    speed: '',
    durability: '',
    distance: '',
    application: 'Kiểm kho, Giao hàng',
    pros: ['Android 12', 'Pin 5100mAh', 'Bàn phím 20 phím', 'Cấu hình 3GB/32GB'],
    cons: ['Giá cao hơn V31'],
    isWireless: true,
    isLongRange: false,
    sensorResolution: '',
    isPDA: true,
    specialFeatures: ['Wifi + 4G'],
    screenSize: '4.0 inch',
    ram: '3 GB',
    cpu: '',
    stock: 0,
    isPriority: false,
    imageUrl: '',
    warranty: '',
    unit: 'Cái',
    accessories: ['Cụ sạc', 'Cáp'],
  },
  {
    id: 'mobydata-vs100-vga',
    name: 'Mobydata VS100 VGA',
    brand: 'Mobydata',
    type: 'Máy quét 2D có dây',
    retailPrice: '.',
    dealerPrice: '.',
    speed: '',
    durability: '',
    distance: '',
    application: 'Bán lẻ, Y tế',
    pros: ['Quét 1D/2D/QR', 'Giá rẻ'],
    cons: ['Có dây', 'Bảo hành 12 tháng'],
    isWireless: false,
    isLongRange: false,
    sensorResolution: 'VGA',
    isPDA: false,
    specialFeatures: [],
    stock: 0,
    isPriority: true,
    imageUrl: 'https://binhduongbarcode.com/thumbs/540x540x1/upload/product/img7916-1743.jpeg',
    warranty: '12 tháng',
    unit: 'Cái',
    accessories: ['Cáp USB'],
  },
];

export const PRINTERS: BarcodePrinter[] = [
  {
    id: 'hprt-ht800',
    name: 'HPRT HT800',
    brand: 'HPRT',
    retailPrice: '3.300.000',
    dealerPrice: '2.960.000',
    resolution: '203 DPI',
    speed: 6,
    width: '110mm (In 108mm)',
    volume: 'Để bàn',
    application: 'Bán lẻ, Tem nhãn',
    pros: ['Giá cạnh tranh', 'Đa kết nối', 'Bền bỉ'],
    isDirectThermal: false,
    stock: 1,
    isPriority: true,
    imageUrl: 'https://binhduongbarcode.com/thumbs/540x540x1/upload/product/hprt-ht830-9307.png',
    connectivity: 'USB 2.0, Ethernet & Serial',
    warranty: '24 tháng',
    unit: 'Cái',
    memory: '256 MB flash & 128 MB SDRAM',
    accessories: ['Cáp USB 2.0', 'Giấy decal 110mm', 'Hướng dẫn sử dụng'],
    notes: 'Mua 20 con tặng 01 con'
  },
  {
    id: 'hprt-ht830',
    name: 'HPRT HT830',
    brand: 'HPRT',
    retailPrice: '4.250.000 VNĐ',
    dealerPrice: '3.680.000 VNĐ',
    resolution: '300 DPI',
    speed: 4,
    width: '110mm (In 106mm)',
    volume: 'Để bàn',
    application: 'Bán lẻ, Tem nhãn chất lượng cao',
    pros: ['Độ phân giải cao', 'In sắc nét', 'Dễ sử dụng'],
    isDirectThermal: false,
    stock: 6,
    isPriority: true,
    imageUrl: 'https://binhduongbarcode.com/thumbs/540x540x1/upload/product/hprt-ht830-9307.png',
    connectivity: 'USB 2.0, Ethernet & Serial',
    warranty: '24 tháng',
    unit: 'Cái',
    memory: '256 MB flash & 128 MB SDRAM',
    accessories: ['Cáp Ethernet', 'Đầu in thay thế', 'Giấy decal 110mm'],
    notes: 'Mua 20 con tặng 01 con'
  },
  {
    id: 'hprt-gala-203',
    name: 'HPRT Gala (203DPI)',
    brand: 'HPRT',
    retailPrice: '16.550.000 VNĐ',
    dealerPrice: '15.255.000 VNĐ',
    resolution: '203 DPI',
    speed: 14,
    width: '110mm (In 104mm)',
    volume: 'Công nghiệp',
    application: 'Sản xuất, Logistics',
    pros: ['Tốc độ in cực nhanh', 'Kết cấu vững chắc', 'Nhiều cổng kết nối'],
    isDirectThermal: false,
    stock: 0,
    isPriority: false,
    imageUrl: 'https://binhduongbarcode.com/upload/elfinder/may-in-hprt-gala3.jpg',
    connectivity: '03 USB 2.0 host, USB 2.0, Ethernet & RS-232',
    warranty: '24 tháng',
    unit: 'Cái',
    memory: '512 MB flash & 256 MB SDRAM',
    accessories: ['Cáp Ethernet', 'Đầu in thay thế', 'Giấy decal 110mm'],
  },
  {
    id: 'hprt-gala-300',
    name: 'HPRT Gala (300DPI)',
    brand: 'HPRT',
    retailPrice: '18.500.000 VNĐ',
    dealerPrice: '17.820.000 VNĐ',
    resolution: '300 DPI',
    speed: 8,
    width: '110mm (In 104mm)',
    volume: 'Công nghiệp',
    application: 'Sản xuất, Tem nhãn sắc nét',
    pros: ['Độ phân giải cao', 'Tốc độ ổn định', 'Bền bỉ'],
    isDirectThermal: false,
    stock: 4,
    isPriority: false,
    imageUrl: 'https://binhduongbarcode.com/upload/elfinder/may-in-hprt-gala3.jpg',
    connectivity: '03 USB 2.0 host, USB 2.0, Ethernet & RS-232',
    warranty: '24 tháng',
    unit: 'Cái',
    memory: '512 MB flash & 256 MB SDRAM'
  },
  {
    id: 'hprt-gala-600',
    name: 'HPRT Gala (600DPI)',
    brand: 'HPRT',
    retailPrice: '-',
    dealerPrice: '-',
    resolution: '600 DPI',
    speed: 4,
    width: '110mm (In 104mm)',
    volume: 'Công nghiệp',
    application: 'Tem nhãn siêu nhỏ, sắc nét',
    pros: ['Độ phân giải siêu cao', 'Chính xác tuyệt đối'],
    isDirectThermal: false,
    stock: 0,
    isPriority: false,
    imageUrl: 'https://binhduongbarcode.com/upload/elfinder/may-in-hprt-gala3.jpg',
    connectivity: '03 USB 2.0 host, USB 2.0, Ethernet & RS-232',
    warranty: '24 tháng',
    unit: 'Cái',
    memory: '256 MB flash & 512 MB SDRAM',
    accessories: ['Cáp Ethernet', 'Giấy decal 110mm', 'Hướng dẫn bảo trì'],
  },
  {
    id: 'hprt-ix4r',
    name: 'HPRT iX4R',
    brand: 'HPRT',
    retailPrice: '42.550.000 VNĐ',
    dealerPrice: '40.070.000 VNĐ',
    resolution: '300 DPI',
    speed: 4,
    width: '110mm (In 104mm)',
    volume: 'Công nghiệp nặng',
    application: 'RFID, Sản xuất quy mô lớn',
    pros: ['Hỗ trợ RFID', 'Màn hình cảm ứng', 'Hiệu suất vượt trội'],
    isDirectThermal: false,
    stock: 2,
    isPriority: false,
    imageUrl: 'https://binhduongbarcode.com/thumbs/540x540x1/upload/product/may-in-ma-vach-cong-nghiep-rfid-idprt-ix4r-1692.jpeg',
    connectivity: '03 USB 2.0 host, USB 2.0, Ethernet & RS-232',
    warranty: '24 tháng',
    unit: 'Cái',
    memory: '256 MB flash & 512 MB SDRAM'
  },
  {
    id: 'zebra-zt411',
    name: 'Zebra ZT411',
    brand: 'Zebra',
    retailPrice: '22.200.000 VNĐ',
    dealerPrice: '20.990.000 VNĐ',
    resolution: '203/300/600 dpi',
    speed: 14,
    width: '4.09" (104 mm)',
    volume: 'Công nghiệp (Cao)',
    application: 'Sản xuất, Phân phối',
    pros: ['Màn hình cảm ứng màu', 'Dễ dàng thay giấy', 'Kết cấu chắc chắn'],
    isDirectThermal: false,
    stock: 3,
    isPriority: true,
    imageUrl: 'https://binhduongbarcode.com/thumbs/540x540x1/upload/product/may-in-ma-vach-zebra-zt411-203dpi-300dpi-8737.png',
    connectivity: 'USB, Serial, Ethernet, Bluetooth',
    warranty: '12 tháng',
    unit: 'Cái',
    memory: '512 MB Flash, 256 MB SDRAM',
    accessories: ['Cáp USB', 'Đầu in thay thế', 'Hướng dẫn cài đặt'],
  },
  
  {
    id: 'zebra-zt231',
    name: 'Zebra ZT231',
    brand: 'Zebra',
    retailPrice: '17.500.000 VNĐ',
    dealerPrice: '16.750.000 VNĐ',
    resolution: '203/300 dpi',
    speed: 12,
    width: '4.09"',
    volume: 'Công nghiệp tầm trung',
    application: 'Kho bãi, Logistics',
    pros: ['Thiết kế nhỏ gọn', 'Dễ vận hành', 'Màn hình cảm ứng'],
    isDirectThermal: false,
    stock: 0,
    isPriority: true,
    imageUrl: 'https://binhduongbarcode.com/thumbs/540x540x1/upload/product/zebra-zt231-3-4436.png',
    connectivity: 'USB, Serial, Ethernet, Bluetooth',
    warranty: '12 tháng',
    unit: 'Cái',
    memory: '256 MB Flash, 256 MB SDRAM'
  },
    {
    id: 'zebra-zt610',
    name: 'Zebra ZT610',
    brand: 'Zebra',
    retailPrice: '58.600.000 VNĐ',
    dealerPrice: '56.700.000 VNĐ',
    resolution: '600 dpi',
    speed: 12,
    width: '4.09"',
    volume: 'Công nghiệp tầm trung',
    application: 'Kho bãi, Logistics',
    pros: ['Thiết kế nhỏ gọn', 'Dễ vận hành', 'Màn hình cảm ứng'],
    isDirectThermal: false,
    stock: 0,
    isPriority: true,
    imageUrl: 'https://binhduongbarcode.com/thumbs/540x540x1/upload/product/thiet-ke-chua-co-ten-3-7926.png',
    connectivity: 'USB, Serial, Ethernet, Bluetooth',
    warranty: '12 tháng',
    unit: 'Cái',
    memory: '2048 MB Flash, 1024 MB SDRAM'
  },
  {
    id: 'zebra-zd230',
    name: 'Zebra ZD230',
    brand: 'Zebra',
    retailPrice: '.',
    dealerPrice: '.',
    resolution: '203 dpi',
    speed: 6,
    width: '4.09"',
    volume: 'Để bàn (Thấp)',
    application: 'Bán lẻ, Vận chuyển',
    pros: ['Giá cả phải chăng', 'Cài đặt đơn giản', 'Đáng tin cậy'],
    isDirectThermal: true,
    stock:0,
    isPriority: true,
    imageUrl: 'https://binhduongbarcode.com/thumbs/540x540x1/upload/product/53761mayintemnhanmavachzebrazd230203dpi1-600x700-5151.jpg',
    connectivity: 'USB (Tùy chọn Ethernet)',
    warranty: '12 tháng',
    unit: 'Cái',
    memory: '256 MB Flash, 128 MB SDRAM'
  },

];

export const PRINTER_ACCESSORIES: PrinterAccessory[] = [
  {
    id: 'ph-203-hprt',
    name: 'Đầu in nhiệt HPRT Gala 203 DPI',
    category: 'Đầu in',
    compatibility: ['HPRT Gala (203DPI)', 'HPRT Gala (300DPI)'],
    price: 'Báo giá',
    stock: 5,
    description: 'Đầu in nhiệt thay thế phù hợp cho máy in HPRT Gala.',
    imageUrl: 'https://binhduongbarcode.com/thumbs/540x540x1/upload/product/prt-new-products-4-inch-thermal-printer-head-mechanism-pt1045-without-cutter-2-4456.jpg',
    notes: 'Thay nhanh trong 15 phút'
  },
  {
    id: 'usb-ab-2m',
    name: 'Cáp USB 2.0 A-B 2m',
    category: 'Cáp kết nối',
    compatibility: ['Zebra DS2208'],
    price: '. VNĐ',
    stock: 1,
    description: 'Cáp dành cho Zebra Ds2208.',
    imageUrl: 'https://binhduongbarcode.com/thumbs/540x540x1/upload/product/day-cap-may-doc-ma-vach-zebra-ds2208-4781.jpg'
  },
  {
    id: 'platen-roller',
    name: 'Trục lăn',
    category: 'Cơ khí',
    compatibility: ['Zebra ZT411 203dpi'],
    price: '.',
    stock: 12,
    description: 'Con lăn ép mực chính hãng, đảm bảo độ bám và ổn định khi in liên tục.',
    imageUrl: 'https://binhduongbarcode.com/thumbs/540x540x1/upload/product/truc-lan-zebra-zt411-8190.png'
  },

];

export const RIBBONS: Ribbon[] = [
  {
    id: 'mw105',
    name: 'Ruy băng in Wax',
    sku: 'MW105',
    spec: '110mm x 300m',
    color: 'Black',
    type: 'Wax',
    retailPrice: '105.000 VNĐ',
    dealerPrice: '48.000 VNĐ',
    dealerPrices: [
      { range: '< 100 cuộn', price: '48.000' },
      { range: '≥ 100 cuộn', price: '47.000' },
      { range: '≥ 300 cuộn', price: '46.000' },
      { range: '≥ 500 cuộn', price: '45.000' }
    ],
    retailPrices: [
      { range: '10 - 20 cuộn', price: '105.000' },
      { range: '20 - 30 cuộn', price: '95.000' },
      { range: '30 - 50 cuộn', price: '85.000' },
      { range: '50 - 100 cuộn', price: '75.000' },
      { range: '> 100 cuộn', price: '65.000' }
    ],
    durability: 'Trung bình',
    adhesion: 'Trung bình',
    material: 'Decal thường, decal bán cảm nhiệt',
    application: 'Vận chuyển, Kiểm kho, Bán lẻ',
    priceRange: 'Thấp',
    imageUrl: 'https://binhduongbarcode.com/thumbs/540x540x1/upload/product/untitled-design-4-2807.png',
    unit: 'Cuộn',
    notes: 'Hàng có sẵn'
  },
  {
    id: 'mp108',
    name: 'Ruy băng in Wax Premium',
    sku: 'MP108',
    spec: '110mm x 300m',
    color: 'Black',
    type: 'Wax',
    retailPrice: '115.000 VNĐ',
    dealerPrice: '54.000 VNĐ',
    dealerPrices: [
      { range: '< 100 cuộn', price: '54.000' },
      { range: '≥ 100 cuộn', price: '53.000' },
      { range: '≥ 300 cuộn', price: '52.000' },
      { range: '≥ 500 cuộn', price: '51.000' }
    ],
    retailPrices: [
      { range: '10 - 20 cuộn', price: '115.000' },
      { range: '20 - 30 cuộn', price: '105.000' },
      { range: '30 - 50 cuộn', price: '95.000' },
      { range: '50 - 100 cuộn', price: '85.000' },
      { range: '> 100 cuộn', price: '70.000' }
    ],
    durability: 'Trung bình',
    adhesion: 'Trung bình',
    material: 'Decal thường, decal bán cảm nhiệt',
    application: 'Bán lẻ, Vận chuyển chất lượng cao',
    priceRange: 'Thấp',
    imageUrl: 'https://binhduongbarcode.com/thumbs/540x540x1/upload/product/untitled-design-4-2807.png',
    unit: 'Cuộn',
    notes: 'Hàng có sẵn'
  },
  {
    id: 'hr621',
    name: 'Ruy băng in Wax Resin',
    sku: 'HR621',
    spec: '110mm x 300m',
    color: 'Black',
    type: 'Wax/Resin',
    retailPrice: '140.000 VNĐ',
    dealerPrice: '98.000 VNĐ',
    dealerPrices: [
      { range: '< 100 cuộn', price: '98.000' },
      { range: '≥ 100 cuộn', price: '95.000' },
      { range: '≥ 300 cuộn', price: '93.000' },
      { range: '≥ 500 cuộn', price: '90.000' }
    ],
    retailPrices: [
      { range: '10 - 20 cuộn', price: '140.000' },
      { range: '20 - 30 cuộn', price: '130.000' },
      { range: '30 - 50 cuộn', price: '120.000' },
      { range: '50 - 100 cuộn', price: '110.000' },
      { range: '> 100 cuộn', price: '100.000' }
    ],
    durability: 'Tốt',
    adhesion: 'Tốt',
    material: 'Decal thường, decal bán cảm nhiệt, decal PVC mờ',
    application: 'Nhãn hóa chất, Ngoài trời',
    priceRange: 'Trung bình',
    imageUrl: 'https://binhduongbarcode.com/thumbs/540x540x1/upload/product/untitled-design-4-2807.png',
    unit: 'Cuộn',
    notes: 'Hàng có sẵn'
  },
  {
    id: 'hr623',
    name: 'Ruy băng in Wax Resin',
    sku: 'HR623',
    spec: '110mm x 300m',
    color: 'Black',
    type: 'Wax/Resin',
    retailPrice: '199.000 VNĐ',
    dealerPrice: '130.000 VNĐ',
    dealerPrices: [
      { range: '< 100 cuộn', price: '130.000' },
      { range: '≥ 100 cuộn', price: '125.000' },
      { range: '≥ 300 cuộn', price: '123.000' },
      { range: '≥ 500 cuộn', price: '120.000' }
    ],
    retailPrices: [
      { range: '10 - 20 cuộn', price: '199.000' },
      { range: '20 - 30 cuộn', price: '189.000' },
      { range: '30 - 50 cuộn', price: '179.000' },
      { range: '50 - 100 cuộn', price: '169.000' },
      { range: '> 100 cuộn', price: '150.000' }
    ],
    durability: 'Tốt',
    adhesion: 'Tốt',
    material: 'Decal thường, decal bán cảm nhiệt, decal PVC mờ, PVC bóng',
    application: 'Nhãn sản phẩm cao cấp',
    priceRange: 'Trung bình',
    imageUrl: 'https://binhduongbarcode.com/thumbs/540x540x1/upload/product/untitled-design-4-2807.png',
    unit: 'Cuộn',
    notes: 'Hàng có sẵn'
  },
  {
    id: 'hr629',
    name: 'Ruy băng in Wax Resin (Kho lạnh)',
    sku: 'HR629',
    spec: '110mm x 300m',
    color: 'Black',
    type: 'Wax/Resin',
    retailPrice: '212.000 VNĐ',
    dealerPrice: '130.000 VNĐ',
    dealerPrices: [
      { range: '< 100 cuộn', price: '130.000' },
      { range: '≥ 100 cuộn', price: '125.000' },
      { range: '≥ 300 cuộn', price: '123.000' },
      { range: '≥ 500 cuộn', price: '120.000' }
    ],
    retailPrices: [
      { range: '10 - 20 cuộn', price: '212.000' },
      { range: '20 - 30 cuộn', price: '202.000' },
      { range: '30 - 50 cuộn', price: '192.000' },
      { range: '50 - 100 cuộn', price: '182.000' },
      { range: '> 100 cuộn', price: '170.000' }
    ],
    durability: 'Tốt',
    adhesion: 'Tốt',
    material: 'Decal thường, decal bán cảm nhiệt, decal PVC mờ',
    application: 'Chuyên dùng trong kho lạnh',
    priceRange: 'Trung bình',
    imageUrl: 'https://binhduongbarcode.com/thumbs/540x540x1/upload/product/untitled-design-4-2807.png',
    unit: 'Cuộn',
    notes: 'Hàng có sẵn'
  },
  {
    id: 'br180',
    name: 'Ruy băng in Resin',
    sku: 'BR180',
    spec: '110mm x 300m',
    color: 'Black',
    type: 'Resin',
    retailPrice: '275.000 VNĐ',
    dealerPrice: '215.000 VNĐ',
    dealerPrices: [
      { range: '< 100 cuộn', price: '215.000' },
      { range: '≥ 100 cuộn', price: '210.000' },
      { range: '≥ 300 cuộn', price: '200.000' },
      { range: '≥ 500 cuộn', price: '195.000' }
    ],
    retailPrices: [
      { range: '10 - 20 cuộn', price: '275.000' },
      { range: '20 - 30 cuộn', price: '265.000' },
      { range: '30 - 50 cuộn', price: '255.000' },
      { range: '50 - 100 cuộn', price: '245.000' },
      { range: '> 100 cuộn', price: '235.000' }
    ],
    durability: 'Rất tốt',
    adhesion: 'Rất tốt',
    material: 'Decal PVC mờ, PVC bóng và xi bạc mờ (Silver)',
    application: 'Điện tử, Ô tô, Môi trường khắc nghiệt',
    priceRange: 'Cao',
    imageUrl: 'https://binhduongbarcode.com/thumbs/540x540x1/upload/product/untitled-design-4-2807.png',
    unit: 'Cuộn',
    notes: 'Hàng có sẵn'
  },
  {
    id: 'br301',
    name: 'Ruy băng in Resin',
    sku: 'BR301',
    spec: '110mm x 300m',
    color: 'Black',
    type: 'Resin',
    retailPrice: '305.000 VNĐ',
    dealerPrice: '240.000 VNĐ',
    dealerPrices: [
      { range: '< 100 cuộn', price: '240.000' },
      { range: '≥ 100 cuộn', price: '230.000' },
      { range: '≥ 300 cuộn', price: '220.000' },
      { range: '≥ 500 cuộn', price: '210.000' }
    ],
    retailPrices: [
      { range: '10 - 20 cuộn', price: '305.000' },
      { range: '20 - 30 cuộn', price: '290.000' },
      { range: '30 - 50 cuộn', price: '280.000' },
      { range: '50 - 100 cuộn', price: '268.000' },
      { range: '> 100 cuộn', price: '250.000' }
    ],
    durability: 'Rất tốt',
    adhesion: 'Rất tốt',
    material: 'Decal PVC mờ, PVC bóng và xi bạc mờ (Silver)',
    application: 'Công nghiệp nặng, Điện tử',
    priceRange: 'Cao',
    imageUrl: 'https://binhduongbarcode.com/thumbs/540x540x1/upload/product/untitled-design-4-2807.png',
    unit: 'Cuộn',
    notes: 'Hàng có sẵn'
  },
  {
    id: 'sr305',
    name: 'Ruy băng in Resin (Chống xăng)',
    sku: 'SR305',
    spec: '110mm x 300m',
    color: 'Black',
    type: 'Resin',
    retailPrice: '360.000 VNĐ',
    dealerPrice: '294.000 VNĐ',
    dealerPrices: [
      { range: '< 100 cuộn', price: '294.000' },
      { range: '≥ 100 cuộn', price: '290.000' },
      { range: '≥ 300 cuộn', price: '285.000' },
      { range: '≥ 500 cuộn', price: '280.000' }
    ],
    retailPrices: [
      { range: '10 - 20 cuộn', price: '360.000' },
      { range: '20 - 30 cuộn', price: '350.000' },
      { range: '30 - 50 cuộn', price: '340.000' },
      { range: '50 - 100 cuộn', price: '320.000' },
      { range: '> 100 cuộn', price: '305.000' }
    ],
    durability: 'Rất tốt',
    adhesion: 'Rất tốt, chống xăng và hóa chất',
    material: 'Decal PVC mờ, PVC bóng và xi bạc mờ (Silver)',
    application: 'Ngành hóa chất, xăng dầu',
    priceRange: 'Cao',
    imageUrl: 'https://binhduongbarcode.com/thumbs/540x540x1/upload/product/untitled-design-4-2807.png',
    unit: 'Cuộn',
    notes: 'Hàng có sẵn'
  },
  {
    id: 'cr150',
    name: 'Ruy băng in Resin (Nhãn vải)',
    sku: 'CR150',
    spec: '110mm x 300m',
    color: 'Black',
    type: 'Resin',
    retailPrice: '365.000 VNĐ',
    dealerPrice: '270.000 VNĐ',
    dealerPrices: [
      { range: '< 100 cuộn', price: '270.000' },
      { range: '≥ 100 cuộn', price: '260.000' },
      { range: '≥ 300 cuộn', price: '255.000' },
      { range: '≥ 500 cuộn', price: '245.000' }
    ],
    retailPrices: [
      { range: '10 - 20 cuộn', price: '365.000' },
      { range: '20 - 30 cuộn', price: '348.000' },
      { range: '30 - 50 cuộn', price: '335.000' },
      { range: '50 - 100 cuộn', price: '322.000' },
      { range: '> 100 cuộn', price: '310.000' }
    ],
    durability: 'Tốt',
    adhesion: 'Tốt',
    material: 'Ruban vải ngành may mặc, nhãn vải, decal vải',
    application: 'Ngành may mặc, thời trang',
    priceRange: 'Cao',
    imageUrl: 'https://binhduongbarcode.com/thumbs/540x540x1/upload/product/untitled-design-4-2807.png',
    unit: 'Cuộn',
    notes: 'Hàng có sẵn'
  },
  {
    id: 'h210g',
    name: 'Ruy băng in Wax Resin (Green)',
    sku: 'H210G',
    spec: '110mm x 300m',
    color: 'Green',
    type: 'Wax/Resin',
    retailPrice: '315.000 VNĐ',
    dealerPrice: '240.000 VNĐ',
    dealerPrices: [
      { range: '< 100 cuộn', price: '240.000' },
      { range: '≥ 100 cuộn', price: '230.000' },
      { range: '≥ 300 cuộn', price: '220.000' },
      { range: '≥ 500 cuộn', price: '195.000' }
    ],
    retailPrices: [
      { range: '10 - 20 cuộn', price: '315.000' },
      { range: '20 - 30 cuộn', price: '302.000' },
      { range: '30 - 50 cuộn', price: '290.000' },
      { range: '50 - 100 cuộn', price: '280.000' },
      { range: '> 100 cuộn', price: '260.000' }
    ],
    durability: 'Tốt',
    adhesion: 'Tốt',
    material: 'Decal thường, decal PVC mờ',
    application: 'Nhãn màu trang trí, phân loại',
    priceRange: 'Trung bình',
    imageUrl: 'https://binhduongbarcode.com/thumbs/540x540x1/upload/product/untitled-design-4-2807.png',
    unit: 'Cuộn',
    notes: 'Hàng có sẵn'
  },
  {
    id: 'h210b',
    name: 'Ruy băng in Wax Resin (Blue)',
    sku: 'H210B',
    spec: '110mm x 300m',
    color: 'Blue',
    type: 'Wax/Resin',
    retailPrice: '315.000 VNĐ',
    dealerPrice: '240.000 VNĐ',
    dealerPrices: [
      { range: '< 100 cuộn', price: '240.000' },
      { range: '≥ 100 cuộn', price: '230.000' },
      { range: '≥ 300 cuộn', price: '220.000' },
      { range: '≥ 500 cuộn', price: '195.000' }
    ],
    retailPrices: [
      { range: '10 - 20 cuộn', price: '315.000' },
      { range: '20 - 30 cuộn', price: '302.000' },
      { range: '30 - 50 cuộn', price: '290.000' },
      { range: '50 - 100 cuộn', price: '280.000' },
      { range: '> 100 cuộn', price: '260.000' }
    ],
    durability: 'Tốt',
    adhesion: 'Tốt',
    material: 'Decal thường, decal PVC mờ',
    application: 'Nhãn màu trang trí, phân loại',
    priceRange: 'Trung bình',
    imageUrl: 'https://binhduongbarcode.com/thumbs/540x540x1/upload/product/untitled-design-4-2807.png',
    unit: 'Cuộn',
    notes: 'Hàng có sẵn'
  },
  {
    id: 'h210r',
    name: 'Ruy băng in Wax Resin (Red)',
    sku: 'H210R',
    spec: '110mm x 300m',
    color: 'Red',
    type: 'Wax/Resin',
    retailPrice: '315.000 VNĐ',
    dealerPrice: '240.000 VNĐ',
    dealerPrices: [
      { range: '< 100 cuộn', price: '240.000' },
      { range: '≥ 100 cuộn', price: '230.000' },
      { range: '≥ 300 cuộn', price: '220.000' },
      { range: '≥ 500 cuộn', price: '195.000' }
    ],
    retailPrices: [
      { range: '10 - 20 cuộn', price: '315.000' },
      { range: '20 - 30 cuộn', price: '302.000' },
      { range: '30 - 50 cuộn', price: '290.000' },
      { range: '50 - 100 cuộn', price: '280.000' },
      { range: '> 100 cuộn', price: '260.000' }
    ],
    durability: 'Tốt',
    adhesion: 'Tốt',
    material: 'Decal thường, decal PVC mờ',
    application: 'Nhãn màu trang trí, phân loại',
    priceRange: 'Trung bình',
    imageUrl: 'https://binhduongbarcode.com/thumbs/540x540x1/upload/product/untitled-design-4-2807.png',
    unit: 'Cuộn',
    notes: 'Hàng có sẵn'
  },
  {
    id: 'h210y',
    name: 'Ruy băng in Wax Resin (Yellow)',
    sku: 'H210Y',
    spec: '110mm x 300m',
    color: 'Yellow',
    type: 'Wax/Resin',
    retailPrice: '340.000 VNĐ',
    dealerPrice: '285.000 VNĐ',
    dealerPrices: [
      { range: '< 100 cuộn', price: '285.000' },
      { range: '≥ 100 cuộn', price: '275.000' },
      { range: '≥ 300 cuộn', price: '265.000' },
      { range: '≥ 500 cuộn', price: '249.000' }
    ],
    retailPrices: [
      { range: '10 - 20 cuộn', price: '340.000' },
      { range: '20 - 30 cuộn', price: '330.000' },
      { range: '30 - 50 cuộn', price: '320.000' },
      { range: '50 - 100 cuộn', price: '310.000' },
      { range: '> 100 cuộn', price: '290.000' }
    ],
    durability: 'Tốt',
    adhesion: 'Tốt',
    material: 'Decal thường, decal PVC mờ',
    application: 'Nhãn màu trang trí, phân loại',
    priceRange: 'Trung bình',
    imageUrl: 'https://binhduongbarcode.com/thumbs/540x540x1/upload/product/untitled-design-4-2807.png',
    unit: 'Cuộn',
    notes: 'Hàng có sẵn'
  },
  {
    id: 'h210br',
    name: 'Ruy băng in Wax Resin (Brown)',
    sku: 'H210BR',
    spec: '110mm x 300m',
    color: 'Brown',
    type: 'Wax/Resin',
    retailPrice: '385.000 VNĐ',
    dealerPrice: '305.000 VNĐ',
    dealerPrices: [
      { range: '< 100 cuộn', price: '305.000' },
      { range: '≥ 100 cuộn', price: '295.000' },
      { range: '≥ 300 cuộn', price: '285.000' },
      { range: '≥ 500 cuộn', price: '275.000' }
    ],
    retailPrices: [
      { range: '10 - 20 cuộn', price: '385.000' },
      { range: '20 - 30 cuộn', price: '375.000' },
      { range: '30 - 50 cuộn', price: '360.000' },
      { range: '50 - 100 cuộn', price: '345.000' },
      { range: '> 100 cuộn', price: '325.000' }
    ],
    durability: 'Tốt',
    adhesion: 'Tốt',
    material: 'Decal thường, decal PVC mờ',
    application: 'Nhãn màu trang trí, phân loại',
    priceRange: 'Trung bình',
    imageUrl: 'https://binhduongbarcode.com/thumbs/540x540x1/upload/product/untitled-design-4-2807.png',
    unit: 'Cuộn',
    notes: 'Hàng có sẵn'
  },
  {
    id: 'dr70',
    name: 'Ruy băng in Wax Resin (Date)',
    sku: 'DR70',
    spec: '110mm x 300m',
    color: 'Black',
    type: 'Wax/Resin',
    retailPrice: '335.000 VNĐ',
    dealerPrice: '260.000 VNĐ',
    dealerPrices: [
      { range: '< 100 cuộn', price: '260.000' },
      { range: '≥ 100 cuộn', price: '250.000' },
      { range: '≥ 300 cuộn', price: '240.000' },
      { range: '≥ 500 cuộn', price: '230.000' }
    ],
    retailPrices: [
      { range: '10 - 20 cuộn', price: '335.000' },
      { range: '20 - 30 cuộn', price: '320.000' },
      { range: '30 - 50 cuộn', price: '305.000' },
      { range: '50 - 100 cuộn', price: '290.000' },
      { range: '> 100 cuộn', price: '270.000' }
    ],
    durability: 'Tốt',
    adhesion: 'Tốt',
    material: 'Màng OPP bóng, máy in ngày sản xuất',
    application: 'In date, hạn sử dụng trên bao bì',
    priceRange: 'Trung bình',
    imageUrl: 'https://binhduongbarcode.com/thumbs/540x540x1/upload/product/untitled-design-4-2807.png',
    unit: 'Cuộn',
    notes: 'Hàng có sẵn'
  }
];

export const LESSONS: Lesson[] = [
  {
    id: 'l1',
    title: 'Phân biệt 1D và 2D Barcode',
    description: 'Kiến thức cơ bản về các loại mã vạch phổ biến.',
    icon: <BarChart3 className="w-6 h-6" />,
    content: [
      'Mã 1D (Linear): Chỉ chứa dữ liệu theo chiều ngang (ví dụ: Code 128, EAN-13).',
      'Mã 2D (Matrix): Chứa dữ liệu cả ngang và dọc (ví dụ: QR Code, Data Matrix).',
      'Máy quét 2D có thể quét được cả mã 1D, nhưng máy quét 1D không quét được mã 2D.'
    ]
  },
  {
    id: 'l2',
    title: 'Cách chọn Máy Quét phù hợp',
    description: 'Tư vấn khách hàng dựa trên nhu cầu thực tế.',
    icon: <Search className="w-6 h-6" />,
    content: [
      '- Môi trường: Nếu kho bãi bụi bặm, chọn IP65 trở lên.',
      '- Khoảng cách: Nếu quét kệ cao, chọn máy quét tầm xa (Long Range).',
      '- Loại mã: Nếu quét mã trên màn hình điện thoại, bắt buộc dùng máy quét 2D chuyên dụng (2D Imager).'
    ]
  },
  {
    id: 'l3',
    title: 'Lựa chọn Mực In (Ribbon)',
    description: 'Tối ưu chi phí và độ bền cho khách hàng.',
    icon: <Layers className="w-6 h-6" />,
    content: [
      'Dùng Wax cho tem nhãn vận chuyển (rẻ, dễ trầy).',
      'Dùng Wax/Resin cho tem nhãn mỹ phẩm, dược phẩm (bền hơn).',
      'Dùng Resin cho tem nhãn điện tử, hóa chất (chống dung môi, nhiệt độ).'
    ]
  },
  {
    id: 'l4',
    title: 'Quy trình Lên đơn & Theo dõi Đơn hàng',
    description: 'Quy trình chuẩn từ báo giá đến khi giao hàng thành công.',
    icon: <GraduationCap className="w-6 h-6" />,
    content: [
      '1. Làm báo giá: Phải đầy đủ tên sản phẩm, thông số kỹ thuật chi tiết, số lượng, tên công ty, địa chỉ công ty, số điện thoại khách hàng...',
      '2. Nhận thông tin đơn hàng: Tiếp nhận PO (Purchase Order) có xác nhận/đóng dấu từ phía công ty khách hàng.',
      '3. Lên đơn hàng: Gửi file cho bộ phận Kế hoạch sản xuất (lưu ý xóa giá trước khi gửi), sau đó mới gửi email đơn hàng đầy đủ cho Kế toán.',
      '4. Thông báo giao hàng: Xác nhận và báo cho khách hàng chính xác ngày dự kiến giao hàng.',
      '5. Theo dõi đơn hàng: Giám sát tiến độ sản xuất và vận chuyển để đảm bảo đúng hẹn.'
    ]
  },
  {
    id: 'l5',
    title: 'Cách chọn Máy In phù hợp',
    description: 'Tư vấn cấu hình máy in dựa trên nhu cầu sử dụng.',
    icon: <Printer className="w-6 h-6" />,
    content: [
      'Số lượng nhãn: Nếu in số lượng lớn (>5000 nhãn/ngày), chọn máy in Công nghiệp; nếu in ít, chọn máy Để bàn.',
      'Kích thước mã vạch: Nếu in mã vạch nhỏ (ví dụ trên linh kiện điện tử), cần chọn máy có độ phân giải cao (300-600 DPI) để đảm bảo độ nét.',
      'Cổng kết nối: Xác định khách hàng cần USB, LAN (Ethernet), RS232 hay Bluetooth/Wifi để chọn model phù hợp.',
      'Độ bền nhãn: Nếu khách hàng cần bảo quản nhãn dài hạn hoặc trong môi trường khắc nghiệt, tư vấn dùng mực Resin hoặc Wax/Resin loại tốt.'
    ]
  },
  {
    id: 'l6',
    title: 'Tính toán Quy cách Tem nhãn',
    description: 'Công thức quy đổi giữa mét dài và số lượng tem.',
    icon: <Calculator className="w-6 h-6" />,
    content: [
      'Khổ ngang (Width): Chiều rộng của con tem (ví dụ: 100mm).',
      'Chiều cao (Height): Chiều dài của con tem theo chiều quấn cuộn (ví dụ: 50mm).',
      'GAP: Khoảng cách giữa 2 con tem liên tiếp (thông thường là 3mm).',
      'Công thức tính số tem: Số tem = Chiều dài cuộn (m) * 1000 / (Chiều cao tem + GAP).',
      'Ví dụ: Cuộn 50m, tem cao 50mm, GAP 3mm => 50 * 1000 / (50 + 3) ≈ 943 tem/cuộn.',
      'Lõi giấy thông dụng: Lõi 1 inch (25mm) cho máy để bàn, Lõi 3 inch (76mm) cho máy công nghiệp.'
    ]
  }
];
